### ISSUE TITLE
<X> DocType Not Found, While 'Bench Update'

### ISSUE THREAD

**Issue by bhattdevarsh** [DigiThinkIT/frappe#236]
## Context

`bench update` is huge Command, which will do all the following task for you in just one go!

1. Update all your instances to the latest app versions.
1. Update dependencies, run patches, and also migrate the database schema.
1. And if executed outside a bench directory, it just updates the bench tool!

## Scenario

Lets consider a bench with 2 sites:

- Site A
- Site B

and the apps installed as:
 
- Site A: `frappe`, `erpnext`, `bloomstack_core`
- Site B: `frappe`, `bloomstack_core`

Here, site B is not fulfilling the dependencies of `bloomstack_core`, which is `erpnext`.

## Issue

When you run `bench update`, site A will proceed and update successfully, but site B will fail trying to resolve its dependencies, but since the `erpnext` app does not exist on the site, it fails with an error: `<X> DocType Not Found`

**Comment by Alchez** [comment]
**Solution**

1. Make sure the base applications for Bloomstack [`frappe`, `erpnext`] are installed before installing any custom app that is dependant on `erpnext`.
